generated_at: '2025-10-18T11:25:02.932895+00:00'
mode: full
tasks:
- slug: docs-readme
  title: Enhance README and API docs
  category: documentation
  phase: Document
  command: IMPROVE_DOCUMENTATION
  params:
    scope: readme
  weight: 3
  tags:
  - docs
  - fdmc:document
- slug: docs-docstrings
  title: Add missing docstrings
  category: documentation
  phase: Develop
  command: ADD_DOCSTRINGS
  params:
    visibility: public
  weight: 2
  tags:
  - docs
  - fdmc:develop
- slug: tests
  title: Expand unit test coverage
  category: testing
  phase: Develop
  command: GENERATE_TESTS
  params:
    coverage_target: '0.85'
  weight: 4
  tags:
  - tests
  - fdmc:develop
- slug: tests-verify
  title: Run test suite with coverage
  category: testing
  phase: Test
  command: RUN_TESTS
  params:
    with_coverage: 'true'
  weight: 2
  tags:
  - tests
  - fdmc:test
- slug: lint
  title: Fix lint and style issues
  category: linting
  phase: Develop
  command: FIX_LINT
  params: {}
  weight: 1
  tags:
  - lint
  - fdmc:develop
- slug: security
  title: Run security scanning
  category: security
  phase: Harden
  command: SECURITY_HARDEN
  params:
    tools: bandit,pip-audit
  weight: 3
  tags:
  - security
  - fdmc:harden
metrics_baseline:
  total_python_files: 9
  functions_without_docstrings: 0
  functions_without_type_hints: 11
  modules_without_tests: 9
  bare_except_blocks: 0
  logging_statements: 0
  todo_count: 55
  workflows_present: true
  pre_commit_present: true
  contributing_present: true
  license_present: true
  code_of_conduct_present: true
  issue_templates_present: true
  pr_template_present: true
  changelog_present: true
  docs_dir_present: false
  coverage_files: 0
  requirements_files: 0
